AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for web app

Parameters:

  ClusterName:
    Description: Name of ECS cluster
    Type: String

  InstanceType:
    Description: EC2 Instance type
    Type: String
    Default: "t2.micro"

  AppImage:
    Description: Name of the image for the app
    Type: String

  AppPort:
    Description: The port the server is listening on
    Type: String


Resources:

  AppCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ClusterName

  EC2RoleForECS:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow server to recieve connections
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref EC2RoleForECS

  EC2LaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: "ami-0dca97e7cde7be3d5"
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${AppCluster} >> /etc/ecs/ecs.config

  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      MinSize: 0
      MaxSize: 1
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref EC2LaunchConfig
      AvailabilityZones:
        - "us-east-2a"
        - "us-east-2b"
        - "us-east-2c"

  AppTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: app
          Memory: 128
          Image: !Ref AppImage
          Environment:
            - Name: HOST_PORT
              Value: !Ref AppPort
          PortMappings:
            - ContainerPort: !Ref AppPort
              HostPort: 80

  AppService:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref AppCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref AppTaskDefinition
